#!/usr/bin/env python3
"""Measure total WAL generated by one caller-controlled PostgreSQL operation."""
from __future__ import annotations
import argparse, json, subprocess, time

def psql(dsn: str, sql: str) -> str:
    return subprocess.run(["psql", dsn, "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-c", sql], check=True, text=True, capture_output=True).stdout.strip()

def measure(dsn: str, sql: str, source: str, config: str) -> dict:
    start = psql(dsn, "select pg_current_wal_lsn()")
    began = time.monotonic()
    try:
        psql(dsn, sql)
    except subprocess.CalledProcessError as exc:
        return {"outcome":"failed", "source":source, "config":config, "wall_seconds":time.monotonic()-began, "error":exc.stderr.strip()}
    end = psql(dsn, "select pg_current_wal_lsn()")
    delta = float(psql(dsn, f"select pg_wal_lsn_diff('{end}','{start}')"))
    return {"outcome":"ok", "source":source, "config":config, "start_lsn":start, "end_lsn":end, "wal_bytes":delta, "wall_seconds":time.monotonic()-began}

def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument("--dsn", required=True); ap.add_argument("--sql", required=True); ap.add_argument("--source", default="caller-operation"); ap.add_argument("--config", default="local-disposable")
    print(json.dumps(measure(**vars(ap.parse_args())), sort_keys=True)); return 0
if __name__ == "__main__": raise SystemExit(main())
