//! #474 A: 1,001 payable recipients across the 1,000-recipient fanout chunk
//! boundary, from accepted work through the spend of an output of each
//! chunk.
//!
//! How the accepted work arrives is part of the claim, so it is counted by
//! source. Most of it is seeded: before any server starts, one share per
//! seeded payee is appended through the production ledger append
//! (`Ledger::append`, writer `SEED_WRITER`), at a weight chosen here. The
//! rest is submitted: `SUBMITTING` payees open real Stratum sessions, on
//! both servers, and submit shares at the seeded unit weight, and one of
//! them finds the block. Two submitting payees are also seeded, so one
//! account combines both sources. This is not 1,001 live mining sessions,
//! and the summary does not say it is.
//!
//! The payout is then recomputed from the ledger and compared with the
//! chain, the ledger's accounts and the signed audit bundle exactly as in the
//! weighted scenarios, and the owning wallets spend the smallest output of
//! each fanout chunk.
use super::*;
use qbit_prism::AcceptedShare;
use qbit_prism_server::ledger::Ledger;

/// Payable payout addresses: one more than a fanout chunk holds.
const RECIPIENTS: usize = MAX_FANOUT_RECIPIENTS + 1;
/// Payees `0..SUBMITTING` submit over Stratum; the rest are seeded only.
const SUBMITTING: usize = 4;
/// Payees `SUBMITTING - BOTH..SUBMITTING` also have a seeded share.
const BOTH: usize = 2;
/// Wallets the 1,001 addresses are generated by, round robin.
const WALLETS: usize = 16;
/// The ledger writer of the seeded shares.
const SEED_WRITER: &str = "seed-474";
/// Payees weigh 1 to `MAX_UNITS` units, so amounts differ up to fourfold.
const MAX_UNITS: u64 = 4;
/// The payout floor for this case: at ~2,500 units of weight over a regtest
/// coinbase every payee's amount stays several times above it.
const BOUNDARY_FLOOR_BITS: u64 = 100_000;

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "nightly: 1,001 recipients across two fanout chunks; run with --ignored"]
async fn nightly_1001_recipients_cross_the_fanout_chunk_boundary_to_spent_outputs() -> Result<()> {
    let Some(mut fixture) = Fixture::open_with_servers(true, false).await? else {
        return Ok(());
    };
    let started = Instant::now();
    let result = run(&mut fixture).await;
    if result.is_err() {
        eprintln!("{}", fixture.diagnostics());
    }
    let cleanup = fixture.cleanup().await;
    eprintln!(
        "live recipient boundary: {:.1}s wall clock including cleanup",
        started.elapsed().as_secs_f64()
    );
    result.and(cleanup)
}

async fn run(fixture: &mut Fixture) -> Result<()> {
    let started = Instant::now();
    let ramp_address = harden_chain(fixture).await?;
    let template = fixture
        .rpc("getblocktemplate", json!([{"rules": ["segwit"]}]))
        .await?;
    let network = block_weight(template["bits"].as_str().context("template bits missing")?)?;
    let height = template["height"]
        .as_u64()
        .context("template height missing")?;
    let ntime = u32::try_from(template["curtime"].as_u64().context("curtime missing")?)?;
    let policy = Policy {
        ctv: true,
        floor: BOUNDARY_FLOOR_BITS,
        pool: pool_identity(fixture).await?,
    };
    let payees = Payees::create(fixture, RECIPIENTS, WALLETS).await?;
    let chain_ready = started.elapsed();

    // Unequal weights in whole units, the unit being one share at the
    // difficulty the submitting sessions use. All of it fits in half the
    // window, so every payee is in the found block's window.
    let mut rng = StdRng::seed_from_u64(0x0474_1001);
    let units: Vec<u64> = (0..RECIPIENTS)
        .map(|_| rng.gen_range(1..=MAX_UNITS))
        .collect();
    let total_units = units.iter().sum::<u64>() + BOTH as u64 + 1;
    let window = network as f64 * qbit_prism::PRISM_WINDOW_MULTIPLIER as f64;
    let difficulty = (window / 2.0 / total_units as f64 / share_weight(1.0)? as f64).clamp(
        MIN_DIFFICULTY,
        network as f64 / 2.0 / share_weight(1.0)? as f64,
    );
    let unit = share_weight(difficulty)?;
    ensure!(
        u128::from(total_units) * unit < network * qbit_prism::PRISM_WINDOW_MULTIPLIER,
        "the recipients' work does not fit one window"
    );

    // Seeded work, through the production append, before the servers start
    // and load the window.
    let seeding = Instant::now();
    let seeded = seed(fixture, &payees.ids, &units, unit, network, height, ntime).await?;
    let seeding = seeding.elapsed();

    start_servers(fixture, &policy).await?;
    let mut sessions = Vec::with_capacity(SUBMITTING);
    for payee in 0..SUBMITTING {
        let username = format!("{}.boundary", payees.ids[payee].recipient);
        sessions.push(Session::open(fixture.stratum[payee % 2], username, difficulty).await?);
    }
    let mut submitted: HashMap<String, usize> = HashMap::new();
    let mut stale_retries = 0;
    let mut tasks = tokio::task::JoinSet::new();
    for (payee, mut session) in sessions.into_iter().enumerate() {
        let count = units[payee];
        tasks.spawn(async move {
            let mut shares = Vec::new();
            for _ in 0..count {
                shares.push(session.submit(false).await?);
            }
            Ok::<_, anyhow::Error>((payee, session, shares))
        });
    }
    let mut sessions: Vec<Option<Session>> = (0..SUBMITTING).map(|_| None).collect();
    while let Some(joined) = tasks.join_next().await {
        let (payee, session, shares) = joined??;
        sessions[payee] = Some(session);
        for share in shares {
            stale_retries += share.stale_retries;
            ensure!(
                submitted.insert(share.share_id, payee).is_none(),
                "a share id was acknowledged twice"
            );
        }
    }
    // Let the reanchor publish work over the submitted shares first.
    tokio::time::sleep(Duration::from_millis(1_600)).await;
    let finder = sessions[0].as_mut().context("finder missing")?;
    let block = find_block(fixture, finder, "boundary").await?;
    stale_retries += block.stale_retries;
    ensure!(
        submitted.insert(block.share_id.clone(), 0).is_none(),
        "the block share id was acknowledged twice"
    );
    drop(sessions);
    fixture.quiesce().await?;
    let found = [Found {
        hash: block.hash,
        share_id: block.share_id,
    }];

    let shares = ledger_shares(fixture).await?;
    let sources = check_sources(&shares, &seeded, &submitted, &payees.ids, unit)?;
    let verifying = Instant::now();
    let verified =
        verify_payouts(fixture, &ramp_address, &found, &shares, &policy, &payees).await?;
    let verifying = verifying.elapsed();

    let (window, settled) = verified.expected.first().context("no block verified")?;
    let payable = settled
        .accounts
        .values()
        .filter(|account| account.onchain > 0)
        .count();
    let chunks: Vec<usize> = settled.chunks.iter().map(Vec::len).collect();
    ensure!(
        window.weights.len() == RECIPIENTS && !window.cut,
        "the window holds {} of the {RECIPIENTS} recipients (cut: {})",
        window.weights.len(),
        window.cut
    );
    ensure!(
        payable == RECIPIENTS && settled.accounts.values().all(|account| account.carry == 0),
        "{payable} of {RECIPIENTS} recipients were payable"
    );
    ensure!(
        chunks.len() == 2 && chunks[0] == MAX_FANOUT_RECIPIENTS,
        "fanout chunks {chunks:?} do not cross the {MAX_FANOUT_RECIPIENTS}-recipient boundary"
    );
    // One output of each chunk, and one direct payee output if any.
    let direct_payees = settled
        .direct
        .keys()
        .filter(|script| payees.owners.contains_key(*script))
        .count();
    ensure!(
        verified.spent == chunks.len() + usize::from(direct_payees > 0),
        "{} outputs spent for {} chunks and {direct_payees} direct payees",
        verified.spent,
        chunks.len()
    );
    let amounts: Vec<u64> = settled
        .accounts
        .values()
        .map(|account| account.onchain)
        .collect();
    eprintln!(
        "live recipient boundary: {RECIPIENTS} payable recipients in {WALLETS} wallets; accepted work: \
         {} seeded shares for {} recipients through Ledger::append (writer {SEED_WRITER}), {} shares \
         ({stale_retries} stale retries) submitted over Stratum by {} recipients in {SUBMITTING} live \
         sessions on both servers, {} recipients with both; one block, window of {} shares, not cut; \
         {payable} recipients paid {}..{} bits, direct outputs {}, fanout chunks {chunks:?}, {} bit pool \
         fee; the signed audit bundle matched the model; {} payee outputs (one per chunk) spent by {} \
         owning wallets; wall clock: chain ramp and wallets {:.1}s, seeding {:.1}s, verification, \
         maturity and spend {:.1}s",
        sources.seeded_shares,
        sources.seeded_recipients,
        sources.submitted_shares,
        sources.submitted_recipients,
        sources.both,
        window.shares,
        amounts.iter().min().context("no amounts")?,
        amounts.iter().max().context("no amounts")?,
        settled.direct.len(),
        settled.pool_fee,
        verified.spent,
        verified.spending_wallets,
        chain_ready.as_secs_f64(),
        seeding.as_secs_f64(),
        verifying.as_secs_f64(),
    );
    Ok(())
}

/// Appends one seeded share for each payee from `SUBMITTING - BOTH` on,
/// weighing its units (one unit for the payees that also submit), and
/// returns the seeded share ids with the payee each credits.
async fn seed(
    fixture: &Fixture,
    payees: &[Identity],
    units: &[u64],
    unit: u128,
    network: u128,
    height: u64,
    ntime: u32,
) -> Result<HashMap<String, (usize, u128)>> {
    let ledger =
        Ledger::connect_tool(&fixture.database_url, SEED_WRITER.into(), 2, true, None).await?;
    let result = async {
        // Old enough that every seeded job precedes the found block's.
        let issued = i64::try_from(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)?
                .as_millis(),
        )? - 600_000;
        let mut seeded = HashMap::new();
        for payee in SUBMITTING - BOTH..payees.len() {
            let identity = &payees[payee];
            let weight = if payee < SUBMITTING {
                unit
            } else {
                unit * u128::from(units[payee])
            };
            let offset = i64::try_from(payee)?;
            let share = AcceptedShare {
                share_seq: 0,
                share_id: format!("{SEED_WRITER}:{payee}"),
                miner_id: identity.recipient.clone(),
                order_key: identity.order_key.clone(),
                p2mr_program_hex: identity.program.clone(),
                share_difficulty: weight,
                network_difficulty: network,
                template_height: height,
                job_id: SEED_WRITER.into(),
                job_issued_at_ms: issued + offset,
                accepted_at_ms: issued + offset + 1,
                ntime,
                credit_policy: None,
            };
            seeded.insert(share.share_id.clone(), (payee, weight));
            ledger.append(share, None).await?;
        }
        Ok::<_, anyhow::Error>(seeded)
    }
    .await;
    ledger.pool.close().await;
    result
}

/// How the ledger's accepted work arrived.
struct Sources {
    seeded_shares: usize,
    seeded_recipients: usize,
    submitted_shares: usize,
    submitted_recipients: usize,
    both: usize,
}

/// The ledger holds exactly the seeded shares, under the seed writer, and
/// the shares the servers acknowledged, under the server each session used,
/// each credited to its payee at the unit or seeded weight.
fn check_sources(
    shares: &[LedgerShare],
    seeded: &HashMap<String, (usize, u128)>,
    submitted: &HashMap<String, usize>,
    payees: &[Identity],
    unit: u128,
) -> Result<Sources> {
    ensure!(
        shares.len() == seeded.len() + submitted.len(),
        "ledger holds {} accepted shares; {} were seeded and {} acknowledged",
        shares.len(),
        seeded.len(),
        submitted.len()
    );
    let mut from_seed = BTreeSet::new();
    let mut from_stratum = BTreeSet::new();
    for share in shares {
        let (payee, weight, writer) = if let Some((payee, weight)) = seeded.get(&share.share_id) {
            from_seed.insert(*payee);
            (*payee, *weight, SEED_WRITER.to_owned())
        } else {
            let payee = *submitted.get(&share.share_id).with_context(|| {
                format!("ledger share {} was never acknowledged", share.share_id)
            })?;
            from_stratum.insert(payee);
            (payee, unit, format!("live-{}", payee % 2))
        };
        let identity = &payees[payee];
        ensure!(
            share.miner == identity.recipient
                && share.order_key == identity.order_key
                && share.program == identity.program
                && share.weight == weight
                && share.writer == writer
                && share.credit_policy.is_none(),
            "share {} credited to {} at {} by {}, not {} at {weight} by {writer}",
            share.share_id,
            share.miner,
            share.weight,
            share.writer,
            identity.recipient
        );
    }
    let seeded_recipients = from_seed.len();
    let submitted_recipients = from_stratum.len();
    let both = from_seed.intersection(&from_stratum).count();
    ensure!(
        submitted_recipients == SUBMITTING
            && both == BOTH
            && seeded_recipients + submitted_recipients - both == RECIPIENTS,
        "work came from {seeded_recipients} seeded and {submitted_recipients} submitting \
         recipients, {both} both"
    );
    Ok(Sources {
        seeded_shares: seeded.len(),
        seeded_recipients,
        submitted_shares: submitted.len(),
        submitted_recipients,
        both,
    })
}
