use super::*;
pub(super) fn test_config() -> Config {
    Config {
        database_url: "postgresql://localhost/prism".into(),
        instance_id: "frontend-a".into(),
        database_connections: 4,
        initialize_schema: false,
        chain: "regtest".into(),
        expected_genesis_hash: None,
        min_peers: 1,
        template_max_age: Duration::from_secs(120),
        submit_tip_max_age: Duration::from_secs(10),
        template_refresh_failure_exit: Duration::from_secs(120),
        rpc_url: "http://127.0.0.1:18452/".into(),
        rpc_user: "operator".into(),
        rpc_password: "test-only".into(),
        rpc_timeout: Duration::from_secs(15),
        block_submit_timeout: Duration::from_secs(1),
        poll_interval: Duration::from_secs(2),
        blockwait: true,
        build_workers: 2,
        runtime_workers: 2,
        snapshot_interval: Duration::from_secs(60),
        health_timeout: Duration::from_secs(15),
        share_commit_timeout: Duration::from_secs(15),
        extranonce2_size: 8,
        coinbase_tag: "/PRISM/".into(),
        manifest_seed: "11".repeat(32),
        ledger_seed: "22".repeat(32),
        ledger_public_key: ManifestSigningKey::from_seed_hex(&"22".repeat(32))
            .unwrap()
            .public_key_hex(),
        username_fallback: None,
        payout_policy: qbit_prism::PayoutPolicy::day_one_default(),
        fee_address: None,
        ctv_enabled: false,
        ctv_config: qbit_prism::SettlementModeConfig::default(),
        ctv_direct_floor: 10_485_760,
        ctv_fee: None,
        ctv_fee_premium_bps: 12000,
        ctv_broadcast: false,
        ctv_broadcast_interval: Duration::from_secs(10),
        version_mask: 0x1fffe000,
        audit_bind: "127.0.0.1".into(),
        audit_port: 3341,
    }
}
